smoother_server:
  ros__parameters:
    use_sim_time: false

    # REQUIRED
    costmap_topic: /costmap
    footprint_topic: /base_footprint

    global_frame: map
    robot_base_frame: base_link

    smoother_plugins: ["simple_smoother"]

    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true
